package sisconlojai;

import controleCaixa.AbrirCaixa;
import cadastro.CadUsuario;
import cadastro.CadLoja;
import cadastro.CadFornecedor;
import cadastro.CadFuncionarios;
import cadastro.CadCartao;
import consultar.ConsultarPreco;
import cadastro.CadCliente;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import consultar.*;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import relatorios.RelatorioBandeiraCartao;
import relatorios.RelatorioCategoriaProduto;
import relatorios.RelatorioCliente;
import relatorios.RelatorioEstoque;
import relatorios.RelatorioFinanceiro;
import relatorios.RelatorioFornecedor;
import relatorios.RelatorioFuncionario;
import relatorios.RelatorioLojas;
import relatorios.RelatorioProduto;
import relatorios.RelatorioUsuario;
import relatorios.RelatorioVendas;

/**
 *
 * @author DouglasInfo07
 */
public class PaginaInicial extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

//    Método para mostrar icone da pagina.
    public void IconePagina() {
        URL url = this.getClass().getResource("/imagens/logoDIMTech.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);      
    }
    

    public PaginaInicial() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 3, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SisConLOJAi.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 102));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1330, 120));

        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cadastro.png"))); // NOI18N
        jMenu3.setText("Cadastrar");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jMenu3.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu3.setPreferredSize(new java.awt.Dimension(190, 80));

        jMenuItem7.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/loja.png"))); // NOI18N
        jMenuItem7.setText("Loja / Matriz");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem1.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario1.png"))); // NOI18N
        jMenuItem1.setText("Funcionário");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes.png"))); // NOI18N
        jMenuItem2.setText("Cliente");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fornecedores1.png"))); // NOI18N
        jMenuItem3.setText("Fornecedor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem5.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/produto.png"))); // NOI18N
        jMenuItem5.setText("Produto");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem6.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartao.png"))); // NOI18N
        jMenuItem6.setText("Bandeira Cartão");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem8.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem8.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login.png"))); // NOI18N
        jMenuItem8.setText("Usuário");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/caixa1.png"))); // NOI18N
        jMenu4.setText("Caixa");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jMenu4.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu4.setPreferredSize(new java.awt.Dimension(190, 80));

        jMenuItem9.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem9.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/abrirCaixa.png"))); // NOI18N
        jMenuItem9.setText("Abrir Caixa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem10.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/meuCaixa.png"))); // NOI18N
        jMenuItem10.setText("Meu Caixa");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem11.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem11.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatorioCaixa.png"))); // NOI18N
        jMenuItem11.setText("Relatório Caixa");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem23.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem23.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consultarVenda.png"))); // NOI18N
        jMenuItem23.setText("Consultar Venda");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem23);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/estoque.png"))); // NOI18N
        jMenu5.setText("Estoque");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jMenu5.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu5.setPreferredSize(new java.awt.Dimension(190, 80));

        jMenuItem12.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem12.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/produto.png"))); // NOI18N
        jMenuItem12.setText("Controle Produto");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem15.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem15.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consultarProtuto.png"))); // NOI18N
        jMenuItem15.setText("Consultar Produto");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem15);

        jMenuItem14.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem14.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatotorioProduto.png"))); // NOI18N
        jMenuItem14.setText("Relatório Estoque");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem14);

        jMenuBar1.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Relatorio.png"))); // NOI18N
        jMenu6.setText("Relatórios");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jMenu6.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu6.setPreferredSize(new java.awt.Dimension(190, 80));

        jMenuItem13.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem13.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/funcionario1.png"))); // NOI18N
        jMenuItem13.setText("Funcionário");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem16.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem16.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/clientes.png"))); // NOI18N
        jMenuItem16.setText("Cliente");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuItem17.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem17.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fornecedores1.png"))); // NOI18N
        jMenuItem17.setText("Fornecedor");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem17);

        jMenuItem18.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem18.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/categoria.png"))); // NOI18N
        jMenuItem18.setText("Categoria Produto");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem19.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem19.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/produto.png"))); // NOI18N
        jMenuItem19.setText("Produto");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem19);

        jMenuItem20.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem20.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartao.png"))); // NOI18N
        jMenuItem20.setText("Bandeira Cartão");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem20);

        jMenuItem21.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem21.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/loja.png"))); // NOI18N
        jMenuItem21.setText("Loja / Matriz");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem21);

        jMenuItem22.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem22.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Login.png"))); // NOI18N
        jMenuItem22.setText("Usuário");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem22);

        jMenuItem24.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem24.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/relatotorioProduto.png"))); // NOI18N
        jMenuItem24.setText("Estoque");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem24);

        jMenuItem4.setText("Financeiro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem26.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem26.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consultarVenda.png"))); // NOI18N
        jMenuItem26.setText("Venda");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem26);

        jMenuItem27.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem27.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/meuCaixa.png"))); // NOI18N
        jMenuItem27.setText("Caixa");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem27);

        jMenuBar1.add(jMenu6);

        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/utilitarios.png"))); // NOI18N
        jMenu7.setText("Utilitários");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jMenu7.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu7.setPreferredSize(new java.awt.Dimension(190, 80));

        jMenuItem33.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem33.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem33.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calculadora.png"))); // NOI18N
        jMenuItem33.setText("Calculadora");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem33);

        jMenuItem34.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem34.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem34.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendario.png"))); // NOI18N
        jMenuItem34.setText("Calendário");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem34);

        jMenuItem35.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem35.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem35.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/agendaTelefone.png"))); // NOI18N
        jMenuItem35.setText("Contatos");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem35);

        jMenuItem36.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem36.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem36.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/praLembrar.png"))); // NOI18N
        jMenuItem36.setText("Lembrete");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem36);

        jMenuBar1.add(jMenu7);

        jMenu8.setForeground(new java.awt.Color(255, 255, 255));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/info.png"))); // NOI18N
        jMenu8.setText("Informação");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jMenu8.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu8.setPreferredSize(new java.awt.Dimension(190, 80));

        jMenuItem28.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem28.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem28.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/tutorial.png"))); // NOI18N
        jMenuItem28.setText("Manual");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem28);

        jMenuItem29.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem29.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem29.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logoDIMTech1.png"))); // NOI18N
        jMenuItem29.setText("Versão");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem29);

        jMenuBar1.add(jMenu8);

        jMenu9.setForeground(new java.awt.Color(255, 255, 255));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/sair.png"))); // NOI18N
        jMenu9.setText("Sair");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jMenu9.setMaximumSize(new java.awt.Dimension(200, 32767));
        jMenu9.setPreferredSize(new java.awt.Dimension(190, 80));

        jMenuItem30.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem30.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem30.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logOut.png"))); // NOI18N
        jMenuItem30.setText("Sair usuário");
        jMenu9.add(jMenuItem30);

        jMenuItem31.setBackground(new java.awt.Color(0, 51, 102));
        jMenuItem31.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem31.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/finalizar.png"))); // NOI18N
        jMenuItem31.setText("Sair sistema");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem31);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        CadFuncionarios funcionarios = new CadFuncionarios();
        funcionarios.setVisible(true);
        funcionarios.setTitle("SisCon LOJAi  -  Cadastro de Funcionários");

        funcionarios.setExtendedState(MAXIMIZED_BOTH);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        
        CadCartao cartao = new CadCartao();
        cartao.setVisible(true);
        cartao.setTitle("SisCon LOJAi  -  Cadastro de Cartão Magnético");
                
        cartao.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        
        AbrirCaixa abrirCaixa = new AbrirCaixa();
        abrirCaixa.setVisible(true);
        abrirCaixa.setTitle("SisCon LOJAi  -  Abrir Caixa");
        
        abrirCaixa.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        
        ConsultarProduto consultarProduto = new ConsultarProduto();
        consultarProduto.setVisible(true);
        consultarProduto.setTitle("SisCon LOJAi  -  Consultar Produto");
        
        consultarProduto.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        
        RelatorioFuncionario relatorioFuncionario = new RelatorioFuncionario();
        relatorioFuncionario.setVisible(true);
        relatorioFuncionario.setTitle("SisCon LOJAi  -  Relatório Funcionário");
        
        relatorioFuncionario.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        
        RelatorioBandeiraCartao relatorioBandeiraCartao = new RelatorioBandeiraCartao();
        relatorioBandeiraCartao.setVisible(true);
        relatorioBandeiraCartao.setTitle("SisCon LOJAi  -  Relatório Bandeira Cartão");
        
        relatorioBandeiraCartao.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
       
        RelatorioEstoque relatorioEstoque = new RelatorioEstoque();
        relatorioEstoque.setVisible(true);
        relatorioEstoque.setTitle("SisCon LOJAi  -  Relatório de Estoque");
        
        relatorioEstoque.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed

        File pdf = new File("cd.. src/Manual/teste.pdf"); 
        try { Desktop.getDesktop().open(pdf); } 
        catch(IOException ex) {JOptionPane.showMessageDialog(null, "Erro no Desktop: " + ex); }
                
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
       
        Versao versao = new Versao();
        versao.setVisible(true);
        versao.setTitle("SisCon LOJAi  -  Versão");
        
        versao.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed

        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja realmente fechar o sistema?", "ATENÇÂO USUÁRIO!!!", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        CadFornecedor fornecedor = new CadFornecedor();
        fornecedor.setVisible(true);
        fornecedor.setTitle("SisCon LOJAi  -  Cadastro de Fornecedores");

        fornecedor.setExtendedState(MAXIMIZED_BOTH);
                
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        CadCliente cliente = new CadCliente();
        cliente.setVisible(true);
        cliente.setTitle("SisCon LOJAi  -  Cadastro de Cliente");

        cliente.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        
        CadLoja loja = new CadLoja();
        loja.setVisible(true);
        loja.setTitle("SisCon LOJAi  -  Cadastro de Loja");
        
        loja.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
        ConsultarPreco produto = new ConsultarPreco();
        produto.setVisible(true);
        produto.setTitle("SisCon LOJAi  -  Cadastro de Produtos");
        
        produto.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        CadUsuario usuario = new CadUsuario();
        usuario.setVisible(true);
        usuario.setTitle("SisCon LOJAi  -  Cadastro de Usuários");
        
        usuario.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        
        MeuCaixa meuCaixa = new MeuCaixa();
        meuCaixa.setVisible(true);
        meuCaixa.setTitle("SisCon LOJAi  -  Meu Caixa");
        
        meuCaixa.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

        RelatorioCaixa relatorioCaixa = new RelatorioCaixa();
        relatorioCaixa.setVisible(true);
        relatorioCaixa.setTitle("SisCon LOJAi  -  Relatório de Caixa");
        
        relatorioCaixa.setExtendedState(MAXIMIZED_BOTH); 
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
       
        ConsultaVenda consultarVenda = new ConsultaVenda();
        consultarVenda.setVisible(true);
        consultarVenda.setTitle("SisCon LOJAi  -  Consulta Venda");
        
        consultarVenda.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        
        ControleProduto controleProduto = new ControleProduto();
        controleProduto.setVisible(true);
        controleProduto.setTitle("SisCon LOJAi  -  Controle de Produto");
        
        controleProduto.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        
        RelatorioCliente relatorioCliente = new RelatorioCliente();
        relatorioCliente.setVisible(true);
        relatorioCliente.setTitle("SisCon LOJAi  -  Relatório Cliente");
        
        relatorioCliente.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        
        RelatorioFornecedor relatorioFornecedor = new RelatorioFornecedor();
        relatorioFornecedor.setVisible(true);
        relatorioFornecedor.setTitle("SisCon LOJAi  -  Relatório Fornecedor");
        
        relatorioFornecedor.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        
        RelatorioCategoriaProduto relatorioCategoriaProduto = new RelatorioCategoriaProduto();
        relatorioCategoriaProduto.setVisible(true);
        relatorioCategoriaProduto.setTitle("SisCon LOJAi  -  Relatório Categoria Produto");
        
        relatorioCategoriaProduto.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        
        RelatorioProduto relatorioProduto = new RelatorioProduto();
        relatorioProduto.setVisible(true);
        relatorioProduto.setTitle("SisCon LOJAi  -  Relatório Produto");
        
        relatorioProduto.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed

        RelatorioLojas relatorioLojas = new RelatorioLojas();
        relatorioLojas.setVisible(true);
        relatorioLojas.setTitle("SisCon LOJAi  -  Relatório de Lojas");
        
        relatorioLojas.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        
        RelatorioUsuario relatorioUsuario = new RelatorioUsuario();
        relatorioUsuario.setVisible(true);
        relatorioUsuario.setTitle("SisCon LOJAi  -  Relatório de Usuário");
        
        relatorioUsuario.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
        relatorioFinanceiro.setVisible(true);
        relatorioFinanceiro.setTitle("SisCon LOJAi  -  Relatório de Estoque");
        
        relatorioFinanceiro.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        
        RelatorioVendas relatorioVendas = new RelatorioVendas();
        relatorioVendas.setVisible(true);
        relatorioVendas.setTitle("SisCon LOJAi  -  Relatório de Vendas");
        
        relatorioVendas.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        
        RelatorioCaixa relatorioCaixa = new RelatorioCaixa();
        relatorioCaixa.setVisible(true);
        relatorioCaixa.setTitle("SisCon LOJAi  -  Relatório de Caixa");
        
        relatorioCaixa.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        
        try { 
            Runtime.getRuntime().exec("cmd.exe /C start calc.exe");
        } catch (IOException ex) {
            Logger.getLogger(PaginaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        
        Calendario calendario = new Calendario();
        calendario.setVisible(true);
        calendario.setTitle("SisCon LOJAi  -  Calendário");
        
        calendario.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        
        Lembrete lembrete = new Lembrete();
        lembrete.setVisible(true);
        lembrete.setTitle("SisCon LOJAi  -  Lembrete");
        
        lembrete.setExtendedState(MAXIMIZED_BOTH);
        
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PaginaInicial().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
